config/routes.rb
Rails.application.routes.draw do

  get 'index' => 'static_pages#index'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  post 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'room' => 'rooms#new'
	post 'conference_record/save_record'
	root 'users#new'
	
	resources :users do
		member do
			get :following, :followers
		end

		collection do
			get :autocomplete
		end
	end
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
		if logged_in?
			@micropost = current_user.microposts.build
			@feed_items = current_user.feed
		else
			redirect_to root_url
		end
  end

  def help
  end

	def about
	end

	def contact
	end

	def index
		#render :layout => false
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	<% flash.each do |message_type, message| %>
		<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
	<% end %>
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<%= render 'shared/user_info' %>
			</section>
			<section class="stats">
				<%= render 'shared/stats' %>
			</section>
			<section>
				<%= button_to "Video Call", room_path, method: 'get', class: "btn btn-info" %>
			</section>
			<section class="micropost_form" style="margin-top: 5px">
				<%= bootstrap_form_tag url: 'conference_record/save_record' do |f| %>
					<%= f.file_field :record, html: {multipart: true}, label: "Speech2txt" %>
					<%= f.submit "View Result", class: "btn btn-info", style: "font-size: 10px important" %>
				<% end %>
				<!--%= link_to "View Result", @@stt_url target: "_blank" %!-->
			</section>
			<section class="micropost_form">
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
		<div class="col-md-8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
<% else %>
	<div class="center jumbotron">
		<h1>Welcome to <strong>Vid.conf</strong></h1>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
	</div>
<% end %>