config/routes.rb
Rails.application.routes.draw do

  get 'index' => 'static_pages#index'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  post 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'room' => 'rooms#new'
	post 'conference_record/save_record'
	root 'users#new'
	
	resources :users do
		member do
			get :following, :followers
		end

		collection do
			get :autocomplete
		end
	end
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
<% end %>

app/views/shared/_get_the_app.html.erb
<div class="get-the-app">
	Get the app.
</div>
<div>
	<%= link_to image_tag("app_store.png", size: "150", class: "app-store" ), "http://www.apple.com/itunes/charts/free-apps/", target: '_blank' %>
	<%= link_to image_tag("google_play.png", size: "125", class: "google-play" ), "https://play.google.com/store", target: '_blank'%>
</div>

app/views/shared/_micropost_form.html.erb
<%= cloudinary_js_config %>

<%= bootstrap_form_for(@micropost, html: {multipart: true}) do |f| %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost...", rows: "4" %>
	</div>
	<span class="picture">
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
		<%= f.hidden_field :picture_cache %>
	</span>
	<%= f.submit "Post", class: "btn btn-success" %>
<% end %>

<script type="text/javascript">
	$('#micropost_picture').bind('change', function() {
		var size_in_megabytes = this.files[0].size/1024/1024;
		if (size_in_megabytes > 5) {
			alert('Maximum file size is 5MB. Please choose a smaller file.');
		}
	});
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats follow">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stats">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stats">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= image_tag(current_user.profile_picture.url(:standard), class: "gravatar") %>
<h1 id="name"><%= current_user.name %></h1>
<span class="view_profile"><%= link_to "view profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>