config/routes.rb
Rails.application.routes.draw do

  get 'index' => 'static_pages#index'
  get 'home' => 'static_pages#home'
  get 'help' => 'static_pages#help'
	get 'about' => 'static_pages#about'
	get 'contact' => 'static_pages#contact'
  get 'signup' => 'users#new'
  post 'signup' => 'users#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  get 'room' => 'rooms#new'
	post 'conference_record/save_record'
	root 'users#new'
	
	resources :users do
		member do
			get :following, :followers
		end

		collection do
			get :autocomplete
		end
	end
	resources :account_activations, only: [:edit]
	resources :password_resets, only: [:new, :create, :edit, :update]
	resources :microposts, only: [:create, :destroy]
	resources :relationships, only: [:create, :destroy]

end

app/views/layouts/_body.html.erb
<div class="container">
	<%= yield %>
	<!--%= debug(params) %!-->
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
	<div class="container">
		<%= link_to "Vid.conf", root_path, id: "logo" %>
		<nav>
			<ul class="nav navbar-nav navbar-right">
				<li><%= link_to "Home", home_path, id: "menu" %></li>
				<li><%= link_to "Help", help_path, id: "menu" %></li>
				<% if logged_in? %>
					<li><%= link_to "Users", users_path, id: "menu" %></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown", id="menu">
							Account <b class="caret"></b>
						</a>
						<ul class="dropdown-menu", id="menu">
							<li><%= link_to "Profile", current_user %></li>
							<li><%= link_to "Settings", edit_user_path(current_user) %></li>
							<li class="divider"></li>
							<li>
								<%= link_to "Log out", logout_path, method: "delete", id: "menu" %>
							</li>
						</ul>
					</li>
				<% else %>
					<li><%= link_to "Log in", login_path, id: "menu" %>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag "application", 
				"//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js",
				'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<% if params[:controller] == "users" and params[:action] == "new" %>
		<body class="bg">
			<%= render 'layouts/body' %>
		</body>
	<% elsif params[:controller] == "sessions" and (params[:action] == "new" or params[:action] == "create") %>
		<body class="bg">
			<%= render 'layouts/body' %>
		</body>
	<% else %>
		<body>
			<%= render 'layouts/header' %>
			<%= render 'layouts/body' %>
		</body>
	<% end %>
</html>

app/views/layouts/application_bg.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag "application", 
				"//cdnjs.cloudflare.com/ajax/libs/typeahead.js/0.9.3/typeahead.min.js",
				'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<%= render 'layouts/shim' %>
	</head>
	<body>
		<% if params[:controller] == "users" and params[:action] == "new" %>
		<% elsif params[:controller] == "sessions" and params[:action] == "new" %>
		<% else %>
			<%= render 'layouts/header' %>
		<% end %>
		<div class = "container">
			<% flash.each do |message_type, message| %>
				<%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>